May this year there is increase  in  Goodness of  the world
May this Year there is substacial decrease in Bad tendencies in the world 
May this year we see less hatred in the world
May this year we feel more love in the world
May this year we see ray  of hope in every eyes in the world
May this  year  we feel more secure in the world
Oh  God !!! May these most unexpected things start happening in the world from the year
and may this become our legacy and it goes on!!!!!
and on.....
and on.....
and on.....

I wish all a very happy new Year 2023!!!!!!!!!!!!

